### ISSUE TITLE
Přidání RF přepínače

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFLORA01#2]
Viz issue, [MLAB varianty modulu](https://github.com/mlab-modules/ISM02/issues/6).

**Comment by kaklik** [comment]
Vyřešeno novou konstrukcí TFLORA01B.

**Comment by kaklik** [comment]
Z jakého důvodu je tady ten R2 a C18?  To je z nějakého application note? @ChroustJan 

![image](https://user-images.githubusercontent.com/1194177/149593539-8bbcb96b-c149-4a34-88eb-eb428e24ae24.png)

**Comment by ChroustJan** [comment]
> Tohle už si nepamatuji. Pokud je to nejak důležité musíme se na to podívat. Ale jen tak jsme to tam nedali.
>

Domnívám se, že v tomhle případě je to tam zbytečné a dají se tak ušetřit dvě součástky. Jedinou podmínkou je, aby řídící signál byl veden tak, aby nemohl být zarušen během vysílání.
