### ISSUE TITLE
Stabilita kmitočtové reference

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFLORA01#3]
Semtech doporučuje do zařízení, které vysílají velkým výkonem, nebo pracují za extrémních podmínek použití [TXCO](https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R000000HrYB/w.qo0SCBZWLnZx6SzEJvItJiigKtC9l2XEQe7oivMGA).

![image](https://user-images.githubusercontent.com/1194177/112152950-1ae53c80-8be3-11eb-9d8d-905684ab8521.png)

**Comment by kaklik** [comment]
Přidal jsem do schéma TCXO. Konkrétní součástku je potřeba vybrat z tabulky v datasheetu podle dostupnosti:

![image](https://user-images.githubusercontent.com/1194177/148962461-b4293b96-6b9e-4d3f-ace8-5bcc70c80afa.png)

**Comment by ChroustJan** [comment]
@kaklik koukal jsi se na ty co jsou v tabulce? Mě přijdou dost exotické. A celkově nějak nejsou. Provedl by jsi výběr vhodného? Kdyby bylo pouzdro 3,2x2 (2,5) to by bylo fajn, ale kdyby ne, tak ani těch 1,6x2mm nevadí.

**Comment by kaklik** [comment]
> @kaklik koukal jsi se na ty co jsou v tabulce? Mě přijdou dost exotické. A celkově nějak nejsou. Provedl by jsi výběr vhodného? Kdyby bylo pouzdro 3,2x2 (2,5) to by bylo fajn, ale kdyby ne, tak ani těch 1,6x2mm nevadí.

Tak oni na ty oscilátory jsou totiž taky celkem exotické požadavky. Není jednoduchý najít nějaký úplně dobrý, už jsem se na to díval.

**Comment by kaklik** [comment]
Vybrán oscilátor [ECS-TXO-32CSMV-320-AN-TR](https://eu.mouser.com/datasheet/2/122/ECS_TXO_32CSMV-1663895.pdf)
